# Generated by Django 5.1.1 on 2024-09-30 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("content", models.TextField()),
                ("location", models.CharField(max_length=255)),
                ("call", models.CharField(blank=True, max_length=20, null=True)),
                ("photo", models.ImageField(upload_to="foods_photos/")),
                ("rating", models.DecimalField(decimal_places=1, max_digits=2)),
                (
                    "cuisine",
                    models.CharField(
                        choices=[
                            ("KR", "한식"),
                            ("JP", "일식"),
                            ("CN", "중식"),
                            ("WE", "양식"),
                        ],
                        max_length=2,
                    ),
                ),
                ("parking_available", models.BooleanField(default=False)),
                ("reservation_available", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
