# Generated by Django 5.1.1 on 2024-10-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="cuisine",
            field=models.CharField(
                choices=[
                    ("KR", "한식"),
                    ("WE", "양식"),
                    ("JP", "일식"),
                    ("CN", "중식"),
                ],
                max_length=2,
            ),
        ),
    ]
