# Generated by Django 5.1.1 on 2024-10-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0003_food_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
