# Generated by Django 5.1.1 on 2024-10-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0004_alter_food_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="location_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="food",
            name="location_lng",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
